export const REQUEST_CONTENT_LIST = 'REQUEST_CONTENT_LIST'
export const GET_CONTENT_LIST = 'GET_CONTENT_LIST'
export const GET_CONTENT_LIST_FAILURE = 'GET_CONTENT_LIST_FAILURE'

export const UPDATE_HEADLINE = 'UPDATE_HEADLINE'
export const GET_HEADLINE = 'GET_HEADLINE'

export const GET_ARTICLE = 'GET_ARTICLE'
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE'
export const CLEAR_ARTICLE = 'CLEAR_ARTIVLE'

export const GET_TAGS = 'GET_TAGS'
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE'

export const GET_TAG_CONTENT_LIST = 'GET_TAG_CONTENT_LIST'
export const GET_TAG_CONTENT_LIST_FAILURE = 'GET_TAG_CONTENT_LIST_FAILURE'

export const GET_COMMENTS_LIST = 'GET_COMMENTS_LIST'
export const GET_COMMENTS_LIST_FAILURE = 'GET_COMMENTS_LIST_FAILURE'

export const SUBMIT_COMMENT = 'SUBMIT_COMMENT'
export const SUBMIT_COMMENT_FAILURE = 'SUBMIT_COMMENT_FAILURE'
